apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: dev
spec:
  replicas: 3
  selector:
    # Deployment会匹配与这里设置的相同标签内容的pod
    matchLabels:
      app: nginx
  # pod的模板描述
  template:
    metadata:
      #定义pod的标签
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
