# Use postgres/example user/password credentials
version: '3.8'

services:

  postgres:
    image: postgres:15
    # restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ginchat
      PGDATA: /var/lib/postgresql/data/pgdata //数据存储文件夹
    volumes:
      - D:/Job/docker/pg/data:/var/lib/postgresql/data/pgdata //将数据映射到对应的路径
    ports:
      - 5432:5432
    
